title: Open Operations Manifesto
description: Building a community of practice and transparency for Operations

# Set this to your domain; baseurl is for the folder in your domain, if you have one -- `blog`.
# you can leave both of them blank if you are deploying on a top-level domain.
url: https://openoperations.org

# footer
footer: 'Open Operations Manifesto v0.1 â€“ CC BY-SA'

layout:
  theme_switch: true # enable or disable user toggle switch between light and dark theme
  link_new_tab: true # should external links open in a new tab (true) or in the current tab (false)

markdown: kramdown
highlighter: rouge

permalink: pretty
permalink: /:title/

sass:
  sass_dir: /assets/css/_sass
  style: compressed # nested, compact, expanded or compressed
  sourcemap: never

plugins:
 - jekyll-optional-front-matter # https://github.com/benbalter/jekyll-optional-front-matter
 - jekyll-titles-from-headings # https://github.com/benbalter/jekyll-titles-from-headings/
 - jekyll-seo-tag

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - LICENSE
  - netlify.toml
  - node_modules/
  - oinam-jekyll-*.*
  - oinam-jekyll.gemspec
  - README.*
  - server
  - vendor/
  - .sass-cache/
